version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      - unleash-edge-blue-zone
      - kafka
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    command: sleep infinity
    networks:
      - blue-zone
    environment:
      UNLEASH_APIKEY: '*:development.serviceA'
      UNLEASH_API: http://unleash-edge-blue-zone:3063/api
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: first-topic
  
  unleash-edge-green-zone:
    image: unleashorg/unleash-edge:latest
    depends_on:
      - unleash
    command: edge
    environment:
      UPSTREAM_URL: http://unleash:4242
    networks:
      - green-zone
      - unleash-green-vpn

  unleash-edge-blue-zone:
    image: unleashorg/unleash-edge:latest
    depends_on:
      - unleash
    command: edge
    environment:
      UPSTREAM_URL: http://unleash:4242
    networks:
      - blue-zone
      - unleash-blue-vpn

  unleash:
    image: unleashorg/unleash-server:latest
    depends_on:
      - unleashDb
    ports:
      - "4242:4242"
    environment:
      DATABASE_HOST: unleashDb
      DATABASE_NAME: unleash
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_SSL: false
      INIT_CLIENT_API_TOKENS: '*:development.serviceA'
    networks:
      - unleash-blue-vpn
      - unleash-green-vpn
      - unleash-internal

  unleashDb:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: unleash
    networks:
      - unleash-internal

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-internal
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    restart: on-failure
    networks:
      - kafka-internal
      - blue-zone
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-setup:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    networks:
      - kafka-internal
    command: kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --partitions 1 --replication-factor 1 --topic first-topic
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored

volumes:
  postgres-data:

networks:
  kafka-internal:
  unleash-internal:
  blue-zone:
  green-zone:
  unleash-blue-vpn:
  unleash-green-vpn: