version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      - unleash
    command: sleep infinity
    networks:
      - blue-zone
    environment:
      UNLEASH_APIKEY: '*:development.serviceA'
  
  unleash:
    image: unleashorg/unleash-server:latest
    depends_on:
      - unleashDb
    ports:
      - "4242:4242"
    environment:
      DATABASE_HOST: unleashDb
      DATABASE_NAME: unleash
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_SSL: false
      INIT_CLIENT_API_TOKENS: '*:development.serviceA'
    networks:
      - blue-zone
      - unleash-internal

  unleashDb:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: unleash
    networks:
      - unleash-internal

volumes:
  postgres-data:

networks:
  unleash-internal:
  blue-zone: